# Generated by Django 4.2.11 on 2024-04-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='email',
        ),
    ]
