# Generated by Django 4.2.11 on 2024-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eng', models.IntegerField()),
                ('hin', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('sci', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('total', models.IntegerField()),
                ('perc', models.IntegerField()),
                ('res', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
    ]
