# Generated by Django 4.2.11 on 2024-04-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('nickname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=500)),
                ('avatar', models.ImageField(upload_to='avatar/')),
            ],
        ),
    ]
