# Generated by Django 4.2.11 on 2024-04-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='avatar',
        ),
    ]
