# Generated by Django 4.2.11 on 2024-05-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0003_contacts_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
    ]
